#Uncomment next 2 lines for local Path
filesLocation=C:\\Test\\NEW\\
archiveFileLocation=C:\\Test\\NEW\\
#Uncomment next 2 lines for server Path
#filesLocation=/opt/portable/apache-tomcat-9.0.50/Monitoring/
#archiveFileLocation=/opt/portable/apache-tomcat-9.0.50/Monitoring/